local opt = vim.opt

opt.tabstop = 2
opt.encoding = "utf-8"
opt.shiftwidth = 2
opt.number = true
opt.softtabstop = 2
opt.expandtab = true
opt.smartindent = true
opt.autoindent = true
opt.tabpagemax = 10
opt.termguicolors = true
opt.laststatus = 2
opt.mouse = "a"
opt.hidden = true
opt.swapfile = false
opt.laststatus = 3
opt.timeoutlen = 500
opt.completeopt = {'menu', 'menuone', 'noselect'}
opt.relativenumber = true
opt.showtabline = 2
opt.pumheight = 10
opt.cmdheight = 3
opt.smartcase = true
opt.guifont = "monospace:h17"
opt.numberwidth = 4
opt.scrolloff = 8
opt.sidescrolloff = 8
opt.wrap = false
opt.cursorline = true
opt.signcolumn = "yes"
